### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by ozh** [scriptgeni/yourls-custom-header-footer#1]
A couple suggestions for the readme to help people understand what this is about and if they need it:
- a couple instructions on installing won't hurt :)
- YOURLS version this has been written for, although things should stay compatible in future releases
- screenshots would be very nice, eg show what the admin page looks like and how you could customize header and footer

Regarding the code itself, I didn't really inspect it but I think you're missing something in this code block:
```
	if( $head ) {
		// Validate head_option. ALWAYS validate and sanitize user input.
		// Here, we want the value
		$head = $head;
```

`if ($head) {$head = $head;}` ain't gonna do much :)

Cheers!
Ozh

**Comment by scriptgeni** [comment]
Ow ok, thank you the comment. Can you please edit the code, so I can try to do it the right way next time ? :)

**Comment by ozh** [comment]
Well I'm not sure there's a way to sanitize user input when said user input can be, in your case, any arbitrary code.

You would just need:
```php
if (isset($_POST['head_option'])) {
    yourls_update_option('head_option', $_POST['head_option']);
}
```

**Comment by scriptgeni** [comment]
You're right. they can add any code in head and footer area, so there is no check needed.

Thanks
